
package loginusuario;
import CODE.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static sun.security.jgss.GSSUtil.login;


public class control_usuario extends javax.swing.JFrame {
    
     DefaultTableModel control_usuario;

    
     
    public control_usuario() {
        initComponents();
        
         this.control_usuario = (DefaultTableModel) controlusuarios.getModel();
        
        Mostrardatos("");
    }
     public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        control_usuario.setColumnCount(0);
        control_usuario.setRowCount(0);
        controlusuarios.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
      public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            control_usuario.addColumn("id");
            control_usuario.addColumn("nombre");
            control_usuario.addColumn("usuario");
            control_usuario.addColumn("correo");
            control_usuario.addColumn("contraseña");
            control_usuario.addColumn("id_rol");
            
          
            

            this.controlusuarios.setModel((control_usuario));
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM usuario";
            }
            else{
            sql="SELECT * FROM usuario WHERE nombre='"+valor+"'";
            } 

            String []datos=new String [6];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);    
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            
    

            control_usuario.addRow(datos);
            }
            controlusuarios.setModel(control_usuario);
            }catch(SQLException ex){
            Logger.getLogger(control_usuario.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
      
       public void Limpiar(){
        //Funcion para limpiar los text field existentes
        try{
        userfld1.setText("");
        nombrefield.setText("");
        correofld.setText("");
        passfld.setText("");
        jComboBox1.setSelectedItem("");
      
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passfld = new javax.swing.JPasswordField();
        passwordlabel = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        BTN_insert = new javax.swing.JButton();
        correofld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginlabel = new javax.swing.JLabel();
        userlabel1 = new javax.swing.JLabel();
        userfld1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        controlusuarios = new javax.swing.JTable();
        BTN_DELETE = new javax.swing.JButton();
        BTN_UPDATE = new javax.swing.JButton();
        BTN_REPORTAR = new javax.swing.JButton();
        userlabel2 = new javax.swing.JLabel();
        nombrefield = new javax.swing.JTextField();
        passwordlabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        passfld.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        passwordlabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        passwordlabel.setText("Password:");
        passwordlabel.setToolTipText("");

        userlabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        userlabel.setText("Usuario:");

        BTN_insert.setBackground(new java.awt.Color(204, 255, 102));
        BTN_insert.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        BTN_insert.setText("INSERTAR");
        BTN_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_insertActionPerformed(evt);
            }
        });

        correofld.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginusuario/img/logo celucel1.jpg"))); // NOI18N

        loginlabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        loginlabel.setText("control de usuarios");

        userlabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        userlabel1.setText("Correo:");

        userfld1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        userfld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfld1ActionPerformed(evt);
            }
        });

        controlusuarios.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        controlusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        controlusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(controlusuarios);

        BTN_DELETE.setBackground(new java.awt.Color(153, 255, 153));
        BTN_DELETE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        BTN_DELETE.setText("BORRAR");
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });

        BTN_UPDATE.setBackground(new java.awt.Color(153, 153, 255));
        BTN_UPDATE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        BTN_UPDATE.setText("ACTUALIZAR");
        BTN_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UPDATEActionPerformed(evt);
            }
        });

        BTN_REPORTAR.setBackground(new java.awt.Color(153, 255, 153));
        BTN_REPORTAR.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        BTN_REPORTAR.setText("REPORTAR");
        BTN_REPORTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REPORTARActionPerformed(evt);
            }
        });

        userlabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        userlabel2.setText("Nombre:");

        nombrefield.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        passwordlabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        passwordlabel1.setText("Rol:");
        passwordlabel1.setToolTipText("");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2" }));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginusuario/img/backicon.png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginlabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordlabel)
                                    .addComponent(passwordlabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrefield, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passfld, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(userlabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(correofld, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(userlabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(userfld1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userlabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_DELETE)
                        .addGap(58, 58, 58)
                        .addComponent(BTN_UPDATE)
                        .addGap(44, 44, 44)
                        .addComponent(BTN_REPORTAR)
                        .addGap(192, 192, 192))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backbtn)))
                .addGap(18, 18, 18)
                .addComponent(loginlabel)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userlabel)
                            .addComponent(userfld1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userlabel1)
                            .addComponent(correofld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userlabel2)
                            .addComponent(nombrefield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passfld, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_REPORTAR)
                    .addComponent(BTN_UPDATE)
                    .addComponent(BTN_DELETE)
                    .addComponent(BTN_insert))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_insertActionPerformed
        // TODO add your handling code here:
       String user,clave,mail,nombre;
       String rol;
         
        user = userfld1.getText();
       nombre = nombrefield.getText();
        mail = correofld.getText();
        clave = String.valueOf(passfld.getPassword());
        rol = (String) jComboBox1.getSelectedItem();
        
        PreparedStatement ps;
        ResultSet rs;
     
        String query = "INSERT INTO usuario(`ID_user`,`nombre`,`User`,`correo_electronico`,`Password`,`id_rol`) VALUES(0,?,?,?,?,?)";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
         
            ps.setString(1, nombre);
            ps.setString(2, user);
            ps.setString(3, mail);
            ps.setString(4, clave);
            ps.setString(5, rol);
            
                  
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Agregado", "Usuario insertado",2);
                Mostrardatos("");
                Limpiar();
            }
            else{
                    JOptionPane.showMessageDialog(null, "error","lo sentimos ha ocurrido un error",2);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(control_usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_BTN_insertActionPerformed

    private void controlusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlusuariosMouseClicked
        // TODO add your handling code here:
        
         try {
            String Nombre= (String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),1); 
           String Usuario = (String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),2); 
           String Email = (String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),3);
           String Contraseña = (String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),4); 
           String rol =(String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),5);
            userfld1.setText(Usuario);
           correofld.setText(Email); 
           passfld.setText(Contraseña); 
           jComboBox1.setSelectedItem(rol);
             nombrefield.setText(Nombre); 
       
           
           
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex); }
        
        
    }//GEN-LAST:event_controlusuariosMouseClicked

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed
        // TODO add your handling code here:
        
        String id =(String) control_usuario.getValueAt(controlusuarios.getSelectedRow(),0);
         
        PreparedStatement ps;
        String query = "DELETE FROM usuario WHERE ID_User=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, id);

            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "usuario eliminado"); 
                Limpiar();
                RefrescarTabla();
                Mostrardatos("");

            }

        } catch (SQLException ex) {
            Logger.getLogger(control_usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void BTN_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UPDATEActionPerformed
        // TODO add your handling code here:
        
         String user,clave,mail,id,nombre,rol;
        
        user = userfld1.getText();
        mail = correofld.getText();
         rol = (String) jComboBox1.getSelectedItem();
        nombre = nombrefield.getText();
        clave = String.valueOf(passfld.getPassword());
        id = (String)control_usuario.getValueAt(controlusuarios.getSelectedRow(),0);
        

        PreparedStatement ps;
        String query = "UPDATE usuario SET  nombre=? ,User=?, correo_electronico=?, Password=?, id_rol=? WHERE ID_User=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

          ps.setString(6, id);
           ps.setString(1, nombre);
           ps.setString(2, user);
            ps.setString(3, mail);
            ps.setString(4, clave);
            ps.setString(5, rol);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "actualizado correctamente");
             Limpiar();
             Mostrardatos("");

        } catch (SQLException ex) {
            Logger.getLogger(control_usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_BTN_UPDATEActionPerformed

    private void BTN_REPORTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REPORTARActionPerformed
        // TODO add your handling code here:
        
        Connection cn=MyConnection.getConnection();
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(control_usuario.class.getResource("/reportes/usuario.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte Usuarios");

            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_BTN_REPORTARActionPerformed

    private void userfld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfld1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         menu_admin mf = new menu_admin ();
                mf.setVisible(true);
                mf.pack();
                mf.setLocationRelativeTo(null);
                
                this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(control_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(control_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(control_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(control_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new control_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_DELETE;
    private javax.swing.JButton BTN_REPORTAR;
    private javax.swing.JButton BTN_UPDATE;
    private javax.swing.JButton BTN_insert;
    private javax.swing.JButton backbtn;
    private javax.swing.JTable controlusuarios;
    private javax.swing.JTextField correofld;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JTextField nombrefield;
    private javax.swing.JPasswordField passfld;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel passwordlabel1;
    private javax.swing.JTextField userfld1;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel userlabel1;
    private javax.swing.JLabel userlabel2;
    // End of variables declaration//GEN-END:variables
}
